# Generated by Django 2.1.2 on 2018-10-12 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20181011_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransactionreport',
            name='cbalance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='fundtransactionreport',
            name='obalance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
