# Generated by Django 2.1.2 on 2018-11-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_adverisements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverisements',
            name='adtext',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
