# Generated by Django 2.1.2 on 2018-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20181108_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='mobileno',
            field=models.CharField(blank=True, default='No Value', max_length=15, null=True),
        ),
    ]
