# Generated by Django 2.1.2 on 2018-11-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20181109_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adverisements',
            options={'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='balancetransactionreport',
            options={'verbose_name_plural': 'Balance Transaction Report'},
        ),
        migrations.AlterModelOptions(
            name='datacardassignments',
            options={'verbose_name_plural': 'Datacard Assignments Report'},
        ),
        migrations.AlterModelOptions(
            name='datacardproducts',
            options={'verbose_name_plural': 'Datacard Products'},
        ),
        migrations.AlterModelOptions(
            name='dcardbrands',
            options={'verbose_name_plural': 'Datacard Brands'},
        ),
        migrations.AlterModelOptions(
            name='dcarduplogs',
            options={'verbose_name_plural': 'Datacard Csv Uploaded History'},
        ),
        migrations.AlterModelOptions(
            name='dcardupproducts',
            options={'verbose_name_plural': 'Vcloud Csv Products History'},
        ),
        migrations.AlterModelOptions(
            name='fundtransactionreport',
            options={'verbose_name_plural': 'Payment Transaction Report'},
        ),
        migrations.AlterModelOptions(
            name='rcardassignments',
            options={'verbose_name_plural': 'Rcard Assignment Report'},
        ),
        migrations.AlterModelOptions(
            name='rcardbrands',
            options={'verbose_name_plural': 'Rcard Brands'},
        ),
        migrations.AlterModelOptions(
            name='rcardproducts',
            options={'verbose_name_plural': 'Rcard Products'},
        ),
        migrations.AlterModelOptions(
            name='rcarduplogs',
            options={'verbose_name_plural': 'Rcard Csv Uploaded History'},
        ),
        migrations.AlterModelOptions(
            name='rcardupproducts',
            options={'verbose_name_plural': 'Rcard Csv Product History'},
        ),
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name_plural': 'User Registration Details'},
        ),
        migrations.AlterModelOptions(
            name='vcloudassignments',
            options={'verbose_name_plural': 'Vcloud Assignment Reports'},
        ),
        migrations.AlterModelOptions(
            name='vcloudbrands',
            options={'verbose_name_plural': 'Vcloud Brands'},
        ),
        migrations.AlterModelOptions(
            name='vcloudproducts',
            options={'verbose_name_plural': 'Vcloud Products'},
        ),
        migrations.AlterModelOptions(
            name='vcloudtransactions',
            options={'verbose_name_plural': 'Transaction Report'},
        ),
        migrations.AlterModelOptions(
            name='vclouduplogs',
            options={'verbose_name_plural': 'Vcloud Csv Uploaded History'},
        ),
        migrations.AlterModelOptions(
            name='vcloudupproducts',
            options={'verbose_name_plural': 'Vcloud Csv Products History'},
        ),
    ]
