# Generated by Django 2.1.2 on 2018-11-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20181110_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcardupproducts',
            options={'verbose_name_plural': 'Dcard Csv Products History'},
        ),
    ]
