# Generated by Django 2.1.2 on 2018-11-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20181110_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcardupproducts',
            options={'verbose_name_plural': 'Datacard Csv Products History'},
        ),
        migrations.AlterModelOptions(
            name='rcardassignments',
            options={'verbose_name_plural': 'Rcard Assignments Report'},
        ),
        migrations.AlterModelOptions(
            name='vcloudassignments',
            options={'verbose_name_plural': 'Vcloud Assignments Report'},
        ),
    ]
