# Generated by Django 2.1.4 on 2018-12-15 16:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20181110_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('logdesc', models.TextField(default='User', max_length=10000)),
            ],
            options={
                'verbose_name_plural': 'PurchaseLog',
                'db_table': 'purchaselog',
            },
        ),
        migrations.AddField(
            model_name='balancetransactionreport',
            name='cramount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='balancetransactionreport',
            name='nbalance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='balancetransactionreport',
            name='pbalance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='datacardproducts',
            name='fileid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.dcarduplogs'),
        ),
        migrations.AddField(
            model_name='rcardproducts',
            name='fileid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.rcarduplogs'),
        ),
        migrations.AddField(
            model_name='vcloudproducts',
            name='fileid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.vclouduplogs'),
        ),
        migrations.AddField(
            model_name='vcloudtransactions',
            name='rtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datacardproducts',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dcardupproducts',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rcardproducts',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rcardupproducts',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vcloudproducts',
            name='password',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vcloudproducts',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vcloudupproducts',
            name='password',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vcloudupproducts',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
