# Generated by Django 2.1.4 on 2018-12-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20181215_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcloudtransactions',
            name='product_id',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
