# Generated by Django 2.1.3 on 2018-12-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20181221_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcloudproducts',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
