# Generated by Django 2.1.3 on 2018-12-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20181224_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcloudupproducts',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
