# Generated by Django 2.1.4 on 2018-12-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20181224_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcloudtransactions',
            name='sponser1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vclouduser_data_sponser1', to='App.UserData'),
        ),
        migrations.AddField(
            model_name='vcloudtransactions',
            name='sponser2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vclouduser_data_sponser2', to='App.UserData'),
        ),
        migrations.AddField(
            model_name='vcloudtransactions',
            name='sponser3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vclouduser_data_sponser3', to='App.UserData'),
        ),
        migrations.AddField(
            model_name='vcloudtransactions',
            name='sponser4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vclouduser_data_sponser4', to='App.UserData'),
        ),
    ]
