# Generated by Django 2.1.4 on 2018-12-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_vcloudproducts_productstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcloudproducts',
            name='productstatus',
        ),
    ]
