# Generated by Django 2.1.4 on 2018-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_vcloudproducts_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcloudproducts',
            name='productstatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
