# Generated by Django 2.1.4 on 2018-12-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_vcloudproducts_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacardproducts',
            name='productstatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='rcardproducts',
            name='productstatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
